# focus_config.py - Calibrated Configuration
# Generated by calibration system on 2025-09-20 02:35:16

# --- Core Detection Thresholds (CALIBRATED) ---
# Quality Score: 100/100

# Eye Aspect Ratio (EAR) thresholds
EAR_BLINK_THRESHOLD = 0.158
EAR_SLEEPY_THRESHOLD = 0.227

# Head pose thresholds
YAW_DISTRACT_THRESHOLD_RATIO = 1.50
PITCH_DISTRACT_THRESHOLD_RATIO_HIGH = 0.61
PITCH_DISTRACT_THRESHOLD_RATIO_LOW = 0.20

# Frame count thresholds
SLEEPY_FRAME_COUNT = 25
DISTRACT_FRAME_COUNT = 20

# Mouth Aspect Ratio (MAR) threshold for yawn detection
MAR_YAWN_THRESHOLD = 0.85

# --- Technical Parameters ---
NOFACE_TOLERANCE_FRAMES = 15
EAR_SMOOTH_WINDOW = 3
CAM_INDEX = 0
AUDIO_ALERT_TIME = 4.0

# --- Calibration Statistics ---
# EAR Statistics: Mean=0.258, Std=0.066
# EAR Range: 0.062 to 0.656
